# Generated by Django 6.0.2 on 2026-02-19 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client_name', models.CharField(max_length=120)),
                ('client_email', models.EmailField(max_length=254)),
                ('ingreso_mensual', models.FloatField()),
                ('gastos_mensuales', models.FloatField()),
                ('antiguedad_laboral_meses', models.FloatField()),
                ('label', models.IntegerField()),
                ('status', models.CharField(max_length=80)),
                ('monto_maximo', models.BigIntegerField()),
                ('proba_json', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
